database:
  host: localhost
  port: 5432
  user: postgres
  password: 1
  dbname: osg_arch
server:
  host: localhost
  port: 8080
casbin:
  model: ./internal/middleware/config/config.conf
  policy: ./internal/middleware/config/models.csv
jwt:
  signingkey: secret
  expire: 24
  refreshkey: refresh
  rexpire: 24
environment: development